sudo: false
language: python
python:
  - "3.4"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -e .
  - pip install nose django_nose ddt
  - pip install python-coveralls
  - pip install tox-travis

script:
  - tox
  - coverage run --source dedal runtests.py

after_success:
  - coveralls
